/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostello.view;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
/**
 *
 * @author user
 */
public class LoginView extends javax.swing.JFrame {
    boolean isVisible= false;
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        setTitle("Login Screen");
        setLayout(new BorderLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailEnrryLogin = new javax.swing.JTextField();
        EmailEntryLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        LoginButtonLoginPage = new javax.swing.JButton();
        ForgotPasswLabel = new javax.swing.JLabel();
        DHAALogin = new javax.swing.JLabel();
        SignupLogin = new javax.swing.JLabel();
        ShowHide = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EmailEnrryLogin.setBackground(new java.awt.Color(197, 203, 227));
        EmailEnrryLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailEnrryLoginActionPerformed(evt);
            }
        });

        EmailEntryLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        EmailEntryLabel.setForeground(new java.awt.Color(124, 131, 138));
        EmailEntryLabel.setText("Email");

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(124, 131, 138));
        PasswordLabel.setText("Password");

        LoginButtonLoginPage.setBackground(new java.awt.Color(196, 213, 151));
        LoginButtonLoginPage.setText("Login");

        ForgotPasswLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ForgotPasswLabel.setForeground(new java.awt.Color(124, 131, 138));
        ForgotPasswLabel.setText("Forgot Password?");

        DHAALogin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DHAALogin.setForeground(new java.awt.Color(124, 131, 138));
        DHAALogin.setText("Don't have an account? Create one for free!");

        SignupLogin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        SignupLogin.setForeground(new java.awt.Color(51, 51, 255));
        SignupLogin.setText("Signup");
        SignupLogin.setToolTipText("");

        ShowHide.setBackground(new java.awt.Color(204, 204, 204));
        ShowHide.setText("Show");
        ShowHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowHideActionPerformed(evt);
            }
        });

        jPasswordField1.setBackground(new java.awt.Color(197, 203, 227));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagepicker/hos.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel2)
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailEntryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EmailEnrryLogin, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ShowHide))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DHAALogin)
                                    .addComponent(LoginButtonLoginPage)
                                    .addComponent(SignupLogin)
                                    .addComponent(ForgotPasswLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EmailEntryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailEnrryLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShowHide))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ForgotPasswLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginButtonLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DHAALogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupLogin)
                .addGap(93, 93, 93))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void EmailEnrryLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailEnrryLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailEnrryLoginActionPerformed

    private void ShowHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowHideActionPerformed
    if(isVisible){
            jPasswordField1.setEchoChar('*');
            ShowHide.setText("Show");
        } else{
            jPasswordField1.setEchoChar((char) 0);
            ShowHide.setText("Hide");
        }
        isVisible= !isVisible;        // TODO add your handling code here:
    }//GEN-LAST:event_ShowHideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DHAALogin;
    private javax.swing.JTextField EmailEnrryLogin;
    private javax.swing.JLabel EmailEntryLabel;
    private javax.swing.JLabel ForgotPasswLabel;
    private javax.swing.JButton LoginButtonLoginPage;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton ShowHide;
    private javax.swing.JLabel SignupLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
