/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ACER
 */
public class LoginView extends javax.swing.JFrame {
   boolean isVisible= false;
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }
 public String getEmailTextField() {
        return txtEmail.getText().trim();
    }

    public String getPasswordField() {
        return new String(pwdPassword.getPassword()).trim();
    }

    public JButton getLoginButton() {
        return btnLogin;
    }

    public JLabel getRedirectLogin() {
        return lblRedirectRegister;
    }
public JLabel getForgotPassword() {
        return forgotPasswordLabel;
    }
    // Place these listener attachment methods here
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblRedirectRegister = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        forgotPasswordLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ShowHideButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEmail.setText("Email: ");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 40, 10));

        btnLogin.setBackground(new java.awt.Color(196, 213, 151));
        btnLogin.setText("Login");
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 190, 30));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblPassword.setText("Password: ");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, 20));

        lblRedirectRegister.setText("Don't have an account? Sign up.");
        getContentPane().add(lblRedirectRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("Login");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));
        getContentPane().add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 190, 30));

        forgotPasswordLabel.setForeground(new java.awt.Color(51, 102, 255));
        forgotPasswordLabel.setText("Reset Password?");
        getContentPane().add(forgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagepicker/hos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 180, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagepicker/grey.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 400));

        ShowHideButton.setText("Show");
        ShowHideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowHideButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShowHideButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowHideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowHideButtonActionPerformed
        // TODO add your handling code here:
        if(isVisible){
            pwdPassword.setEchoChar('*');
            ShowHideButton.setText("Show");
        } else{
            pwdPassword.setEchoChar((char) 0);
            ShowHideButton.setText("Hide");
        }
        isVisible= !isVisible;
    }//GEN-LAST:event_ShowHideButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShowHideButton;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRedirectRegister;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}

