/*-
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author ACER
 */
public class RegisterView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterView
     */
    public RegisterView() {
        initComponents();
    }
 public String getNameInput() {
        return nameField.getText().trim();
    }

    public String getEmailInput() {
        return emailField.getText().trim();
    }

    public String getPasswordInput() {
        return new String(passwordField.getPassword()).trim();
    }

    public JButton getRegisterButton() {
        return registerButton;
    }

    public JLabel getRedirectLoginLabel() {
        return redirectLogin;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLable = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        redirectLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLable.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        TitleLable.setText("SignUp");
        getContentPane().add(TitleLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 140, 70));

        nameLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nameLabel.setText("Name: ");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        registerButton.setBackground(new java.awt.Color(0, 102, 102));
        registerButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, -1, -1));
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 200, 30));

        emailLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        emailLabel.setText("Email: ");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 200, 30));

        passwordLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        passwordLabel.setText("Password: ");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, -1, -1));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 200, 30));

        redirectLogin.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        redirectLogin.setForeground(new java.awt.Color(0, 153, 255));
        redirectLogin.setText("If already have an account go to Login.");
        redirectLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(redirectLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLable;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel redirectLogin;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
