/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ACER
 */
public class RoomView extends javax.swing.JFrame {


    /**
     * Creates new form AdminDashboardView
     */
    public RoomView() {
        initComponents();
        this.setSize(new java.awt.Dimension(650,400));
    }
public JComboBox<String> getRoomStatusComboBox() {
        return roomStatusComboBox;
    }
public void setRoomStatusOptions(String[] options) {
    roomStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(options));
}

public JButton getAssignRoomButton(){
    return assignRoomButton;
}
public void setAssignRoomButtonEnabled(boolean enabled) {
    assignRoomButton.setEnabled(enabled);
}

public JButton getUpdateRoomButton(){
    return updateRoomButton;
}
public void setUpdateButtonEnabled(boolean enabled) {
    updateRoomButton.setEnabled(enabled);
}
public void setUpdateButtonAction(ActionListener action) {
    updateRoomButton.addActionListener(action);
}
public void setUpdateButtonVisible(boolean visible) {
    updateRoomButton.setVisible(visible);
}
public JButton getCheckoutButton(){
    return checkoutButton;
}
public void setCheckoutButtonText(String text) {
    checkoutButton.setText(text);
}


public void setRoomNumber(String number) {
    roomNumberfield.setText(number);
}

public void setRoomType(String type) {
    roomTypefield.setText(type);
}

public void setCostPerMonth(String cost) {
    costPerMonthField.setText(cost);
}

public void setRoomStatus(String status) {
    roomStatusComboBox.setSelectedItem(status);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        roomStatusComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        assignRoomButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        updateRoomButton = new javax.swing.JButton();
        roomTypefield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        costPerMonthField = new javax.swing.JTextField();
        roomNumberfield = new javax.swing.JTextField();
        roomImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setBackground(new java.awt.Color(0, 0, 0));
        welcomeLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        welcomeLabel.setText("Room");
        getContentPane().add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        roomStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Occupied", "Available" }));
        roomStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomStatusComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(roomStatusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Cost per month:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        assignRoomButton.setBackground(new java.awt.Color(0, 102, 0));
        assignRoomButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        assignRoomButton.setForeground(new java.awt.Color(255, 255, 255));
        assignRoomButton.setText("Assign Room");
        assignRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignRoomButtonActionPerformed(evt);
            }
        });
        getContentPane().add(assignRoomButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 40));

        checkoutButton.setBackground(new java.awt.Color(204, 51, 0));
        checkoutButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        checkoutButton.setForeground(new java.awt.Color(255, 255, 255));
        checkoutButton.setText("Check-out");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 140, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Make sure to read our rules and regulations.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Enjoy your stay at Hostello!");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 190, -1));

        updateRoomButton.setBackground(new java.awt.Color(0, 204, 102));
        updateRoomButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updateRoomButton.setForeground(new java.awt.Color(255, 255, 255));
        updateRoomButton.setText("Update Room");
        updateRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRoomButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateRoomButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 150, 40));

        roomTypefield.setForeground(java.awt.Color.lightGray);
        roomTypefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypefieldActionPerformed(evt);
            }
        });
        getContentPane().add(roomTypefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 120, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setText("Room number: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setText("Room type: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Room status: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        costPerMonthField.setForeground(java.awt.Color.lightGray);
        costPerMonthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costPerMonthFieldActionPerformed(evt);
            }
        });
        getContentPane().add(costPerMonthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, -1));

        roomNumberfield.setForeground(java.awt.Color.lightGray);
        roomNumberfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberfieldActionPerformed(evt);
            }
        });
        getContentPane().add(roomNumberfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, -1));

        roomImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagepicker/room.png"))); // NOI18N
        roomImage.setText("jLabel1");
        getContentPane().add(roomImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 310, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRoomButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateRoomButtonActionPerformed

    private void assignRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignRoomButtonActionPerformed
          System.out.println("Assign Room clicked!");
// TODO add your handling code here:
    }//GEN-LAST:event_assignRoomButtonActionPerformed

    private void roomStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomStatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomStatusComboBoxActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void roomTypefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomTypefieldActionPerformed

    private void costPerMonthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costPerMonthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costPerMonthFieldActionPerformed

    private void roomNumberfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNumberfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignRoomButton;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JTextField costPerMonthField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel roomImage;
    private javax.swing.JTextField roomNumberfield;
    private javax.swing.JComboBox<String> roomStatusComboBox;
    private javax.swing.JTextField roomTypefield;
    private javax.swing.JButton updateRoomButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
